version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: coupon_example
    ports:
      - "53306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
