version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: no


#  docker-compose up -d

# redis-cli -h localhost -p 6378